/*
 * Frontend Service
 *
 * Frontend Microservice for the Giò Plants platform.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utils

import (
	"bytes"
	"net/http"
)

// Performs a POST request
func DoPost(u string, bodyData *bytes.Buffer) (*http.Response, error) {
	if bodyData != nil {
		return http.Post(u, "application/json", bodyData)
	}

	return http.Post(u, "application/json", nil)
}
