/*
 * Frontend Service
 *
 * Frontend Microservice for the Giò Plants platform.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"flag"
	"fmt"
	"gio-frontend-ms/pkg/api"
	"log"
	"net/http"
	"os"
)

func main() {
	checkVariables()

	port := flag.Int("port", 8080, "port to be used")

	flag.Parse()

	log.Printf("Server started on port %d", *port)

	router := api.NewRouter()

	p := fmt.Sprintf(":%d", *port)

	log.Fatal(http.ListenAndServe(p, router))
}

func checkVariables() {
	if deviceServiceHost := os.Getenv("API_GATEWAY_HOST"); deviceServiceHost == "" {
		panic("API_GATEWAY_HOST not set.")
	}
	if deviceServicePort := os.Getenv("API_GATEWAY_PORT"); deviceServicePort == "" {
		panic("API_GATEWAY_PORT not set.")
	}
}
