/*
 * Frontend Service
 *
 * Frontend Microservice for the Giò Plants platform.
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"encoding/json"
	"gio-frontend-ms/pkg/logging"
	"gio-frontend-ms/pkg/model"
	"log"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func errorHandler(w http.ResponseWriter, status int, message string) {
	r := model.ApiResponse{Code: status, Message: message}
	w.WriteHeader(status)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if err := json.NewEncoder(w).Encode(r); err != nil {
		log.Println(err)
	}
}

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = logging.Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{

	Route{
		"ListRooms",
		strings.ToUpper(http.MethodGet),
		"/rooms",
		ListRooms,
	},

	Route{
		"GetRoom",
		strings.ToUpper(http.MethodGet),
		"/rooms/{roomId}",
		GetRoom,
	},

	Route{
		"ListDevices",
		strings.ToUpper(http.MethodGet),
		"/rooms/{roomId}/devices",
		ListDevices,
	},

	Route{
		"GetDevice",
		strings.ToUpper(http.MethodGet),
		"/rooms/{roomId}/devices/{deviceId}",
		GetDevice,
	},

	Route{
		"TriggerAction",
		strings.ToUpper(http.MethodPost),
		"/rooms/{roomId}/devices/{deviceId}/actions/{actionName}",
		TriggerAction,
	},
}
